[package]
name = "db_client"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["macros"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.52.1", features = ["full"] }
db_engine = { path = "../db_engine" }
dynamic_label_management = { path = "../dynamic_label_management" }
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
